"use client";
import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { Archive, Eye, Pencil, Plus } from "lucide-react";
import { editorialArticles, EditorialArticle } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice, LoadingState, EmptyState } from "@/components/admin/Notice";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default function ArtigosPage(){
 const [rows,setRows]=useState<EditorialArticle[]>([]),[editing,setEditing]=useState<Partial<EditorialArticle>|null>(null),[preview,setPreview]=useState<Partial<EditorialArticle>|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{setRows((await editorialArticles.list()).results)}catch{setError("Não foi possível carregar os artigos.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);const scheduled=String(f.get("scheduled_for")||"");const data={title:String(f.get("title")),slug:String(f.get("slug")),summary:String(f.get("summary")),body:String(f.get("body")),category:String(f.get("category")),image_url:String(f.get("image_url")),...(scheduled?{editorial_status:"scheduled" as const,scheduled_for:new Date(scheduled).toISOString()}: {})};try{if(editing.id)await editorialArticles.update(editing.id,data);else await editorialArticles.create(data);setEditing(null);setNotice(scheduled?"Artigo agendado.":"Rascunho salvo.");void load()}catch{setError("Não foi possível salvar. Verifique título, slug, imagem e data de agendamento.")}};
 const action=async(a:EditorialArticle,status:"published"|"archived")=>{try{await editorialArticles.update(a.id,{editorial_status:status});setNotice(status==="published"?"Artigo publicado.":"Artigo arquivado.");void load()}catch{setError("Não foi possível atualizar o artigo.")}};
 const localDate=(value?:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
 return <div className="space-y-6"><PageHeader title="Artigos" description="Edite rascunhos, confira a prévia e publique ou agende com segurança." actions={<Button onClick={()=>setEditing({title:"",slug:"",summary:"",body:"",category:"",image_url:""})}><Plus/>Novo artigo</Button>}/>{error&&<Notice kind="error">{error}</Notice>}{notice&&<Notice kind="success">{notice}</Notice>}
 {editing&&<Card><CardContent className="p-5"><form onSubmit={save} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Input name="title" required defaultValue={editing.title} placeholder="Título"/><Input name="slug" defaultValue={editing.slug} placeholder="slug (opcional na criação)"/><Input name="category" defaultValue={editing.category} placeholder="Categoria"/><Input name="image_url" type="url" defaultValue={editing.image_url} placeholder="URL da capa"/></div><Textarea name="summary" defaultValue={editing.summary} placeholder="Resumo"/><Textarea name="body" required className="min-h-48" defaultValue={editing.body} placeholder="Conteúdo do artigo"/><Input name="scheduled_for" type="datetime-local" defaultValue={localDate(editing.scheduled_for)}/><div className="flex gap-2"><Button type="submit">Salvar</Button><Button type="button" variant="outline" onClick={()=>setPreview(editing)}><Eye/>Prévia</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancelar</Button></div></form></CardContent></Card>}
 {preview&&<Card className="border-indigo-300"><CardContent className="space-y-3 p-6">{preview.image_url&&<Image src={preview.image_url} alt="Capa da prévia" width={800} height={450} className="max-h-56 w-auto rounded object-cover" />}<p className="text-sm text-indigo-600">Prévia autenticada · {preview.category||"Sem categoria"}</p><h2 className="text-2xl font-semibold">{preview.title||"Sem título"}</h2>{preview.summary&&<p className="text-slate-500">{preview.summary}</p>}<div className="whitespace-pre-wrap text-sm">{preview.body}</div><Button variant="outline" onClick={()=>setPreview(null)}>Fechar prévia</Button></CardContent></Card>}
 {loading?<LoadingState/>:<Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Artigo</TableHead><TableHead>Origem</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.length===0?<TableRow><TableCell colSpan={4}><EmptyState title="Nenhum artigo."/></TableCell></TableRow>:rows.map(a=><TableRow key={a.id}><TableCell><p className="font-medium">{a.title}</p><p className="text-xs text-slate-500">{a.category||"Sem categoria"}</p></TableCell><TableCell>{a.origin==="manual"?"Manual":"Importado"}</TableCell><TableCell>{a.editorial_status==="scheduled"?"Agendado":a.editorial_status==="draft"?"Rascunho":a.editorial_status==="published"?"Publicado":"Arquivado"}</TableCell><TableCell className="space-x-2 text-right"><Button size="sm" variant="outline" onClick={()=>setEditing(a)} disabled={a.origin!=="manual"}><Pencil/>Editar</Button><Button size="sm" variant="outline" onClick={()=>void action(a,"published")}><Eye/>Publicar</Button><Button size="sm" variant="outline" onClick={()=>void action(a,"archived")}><Archive/>Arquivar</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>}
