"use client";
import Image from "next/image";
import { FormEvent, useEffect, useState } from "react";
import { Archive, Copy, Eye, Pencil, Plus, Search, Sparkles } from "lucide-react";
import { editorialArticles, EditorialArticle } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice, LoadingState, EmptyState } from "@/components/admin/Notice";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { QuestionHtmlEditor } from "@/components/admin/questions/QuestionHtmlEditor";
import { QuestionContent } from "@/components/QuestionContent";

export default function ArtigosPage(){
 const [rows,setRows]=useState<EditorialArticle[]>([]),[overview,setOverview]=useState<{total:number;draft:number;scheduled:number;published:number;archived:number;featured:number}|null>(null),[tab,setTab]=useState("all"),[search,setSearch]=useState(""),[selected,setSelected]=useState<number[]>([]),[articleBody,setArticleBody]=useState(""),[editing,setEditing]=useState<Partial<EditorialArticle>|null>(null),[preview,setPreview]=useState<Partial<EditorialArticle>|null>(null),[error,setError]=useState(""),[notice,setNotice]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);try{const [articles,summary]=await Promise.all([editorialArticles.list({status:tab==="all"?undefined:tab,search}),editorialArticles.overview()]);setRows(articles.results);setOverview(summary);setSelected([])}catch{setError("Não foi possível carregar os artigos.")}finally{setLoading(false)}};useEffect(()=>{const timer=setTimeout(()=>void load(),search?250:0);return()=>clearTimeout(timer)},[tab,search]);
 const openEditor=(article:Partial<EditorialArticle>)=>{setEditing(article);setArticleBody(article.body||"")};
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);const scheduled=String(f.get("scheduled_for")||"");const data={title:String(f.get("title")),slug:String(f.get("slug")),summary:String(f.get("summary")),body:articleBody,category:String(f.get("category")),image_url:String(f.get("image_url")),seo_title:String(f.get("seo_title")),seo_description:String(f.get("seo_description")),tags:String(f.get("tags")).split(",").map(value=>value.trim()).filter(Boolean),is_featured:f.get("is_featured")==="on",is_pinned:f.get("is_pinned")==="on",...(scheduled?{editorial_status:"scheduled" as const,scheduled_for:new Date(scheduled).toISOString()}: {})};try{if(editing.id)await editorialArticles.update(editing.id,data);else await editorialArticles.create(data);setEditing(null);setNotice(scheduled?"Artigo agendado.":"Rascunho salvo.");void load()}catch{setError("Não foi possível salvar. Verifique título, slug, imagem e data de agendamento.")}};
 const action=async(a:EditorialArticle,status:"published"|"archived")=>{try{await editorialArticles.update(a.id,{editorial_status:status});setNotice(status==="published"?"Artigo publicado.":"Artigo arquivado.");void load()}catch{setError("Não foi possível atualizar o artigo.")}};
 const duplicate=async(a:EditorialArticle)=>{try{await editorialArticles.duplicate(a.id);setNotice("Cópia criada como rascunho.");void load()}catch{setError("Não foi possível duplicar este artigo.")}};
 const bulk=async(action:"draft"|"published"|"archived")=>{if(!selected.length)return;try{const result=await editorialArticles.bulk(selected,action);setNotice(`${result.updated} artigo(s) atualizado(s).`);void load()}catch{setError("Não foi possível concluir a ação em massa.")}};
 const localDate=(value?:string|null)=>value?new Date(value).toISOString().slice(0,16):"";
 return <div className="space-y-6"><PageHeader title="Artigos" description="Edite rascunhos, confira a prévia e publique ou agende com segurança." actions={<Button onClick={()=>openEditor({title:"",slug:"",summary:"",body:"",category:"",image_url:"",tags:[]})}><Plus/>Novo artigo</Button>}/>{error&&<Notice kind="error">{error}</Notice>}{notice&&<Notice kind="success">{notice}</Notice>}{overview&&<div className="grid gap-3 sm:grid-cols-3 xl:grid-cols-6">{[["Total",overview.total],["Rascunhos",overview.draft],["Agendados",overview.scheduled],["Publicados",overview.published],["Arquivados",overview.archived],["Destaques",overview.featured]].map(([label,value])=><Card key={String(label)} className="p-3"><p className="text-xs text-slate-500">{label}</p><p className="text-xl font-bold">{value}</p></Card>)}</div>}<Card className="p-3"><div className="flex flex-wrap gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400"/><Input value={search} onChange={e=>setSearch(e.target.value)} className="pl-9" placeholder="Buscar título, resumo ou categoria"/></div>{["all","draft","scheduled","published","archived"].map(status=><Button key={status} size="sm" variant={tab===status?"default":"outline"} onClick={()=>setTab(status)}>{status==="all"?"Todos":status==="draft"?"Rascunhos":status==="scheduled"?"Agendados":status==="published"?"Publicados":"Arquivados"}</Button>)}</div></Card>{selected.length>0&&<Card className="flex items-center gap-2 p-3"><span className="text-sm font-semibold">{selected.length} selecionado(s)</span><Button size="sm" onClick={()=>void bulk("published")}>Publicar</Button><Button size="sm" variant="outline" onClick={()=>void bulk("draft")}>Rascunho</Button><Button size="sm" variant="destructive" onClick={()=>void bulk("archived")}>Arquivar</Button></Card>}
 {editing&&<Card><CardContent className="p-5"><form onSubmit={save} className="space-y-3"><div className="grid gap-3 sm:grid-cols-2"><Input name="title" required defaultValue={editing.title} placeholder="Título"/><Input name="slug" defaultValue={editing.slug} placeholder="slug (opcional na criação)"/><Input name="category" defaultValue={editing.category} placeholder="Categoria"/><Input name="image_url" type="url" defaultValue={editing.image_url} placeholder="URL da capa"/></div><Textarea name="summary" defaultValue={editing.summary} placeholder="Resumo"/><div className="grid gap-3 sm:grid-cols-2"><Input name="seo_title" defaultValue={editing.seo_title} placeholder="Título SEO"/><Input name="seo_description" defaultValue={editing.seo_description} placeholder="Descrição SEO (até 160 caracteres)"/><Input name="tags" defaultValue={editing.tags?.join(", ")} placeholder="Etiquetas separadas por vírgula"/><div className="flex items-center gap-4 text-sm"><label className="flex gap-2"><input name="is_featured" type="checkbox" defaultChecked={editing.is_featured}/>Destaque</label><label className="flex gap-2"><input name="is_pinned" type="checkbox" defaultChecked={editing.is_pinned}/>Fixar</label></div></div><div className="space-y-2"><label className="text-sm font-semibold">Conteúdo do artigo</label><QuestionHtmlEditor value={articleBody} onChange={setArticleBody} placeholder="Escreva o conteúdo do artigo..." /></div><Input name="scheduled_for" type="datetime-local" defaultValue={localDate(editing.scheduled_for)}/><div className="flex gap-2"><Button type="submit">Salvar</Button><Button type="button" variant="outline" onClick={()=>setPreview(editing)}><Eye/>Prévia</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancelar</Button></div></form></CardContent></Card>}
 {preview&&<Card className="border-indigo-300"><CardContent className="space-y-3 p-6">{preview.image_url&&<Image src={preview.image_url} alt="Capa da prévia" width={800} height={450} className="max-h-56 w-auto rounded object-cover" />}<p className="text-sm text-indigo-600">Prévia autenticada · {preview.category||"Sem categoria"}</p><h2 className="text-2xl font-semibold">{preview.title||"Sem título"}</h2>{preview.summary&&<p className="text-slate-500">{preview.summary}</p>}<QuestionContent text={preview.body||""} className="text-sm leading-7" /><Button variant="outline" onClick={()=>setPreview(null)}>Fechar prévia</Button></CardContent></Card>}
 {loading?<LoadingState/>:<Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead><input type="checkbox" checked={rows.length>0&&selected.length===rows.length} onChange={()=>setSelected(selected.length===rows.length?[]:rows.map(a=>a.id))}/></TableHead><TableHead>Artigo</TableHead><TableHead>Origem</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{rows.length===0?<TableRow><TableCell colSpan={5}><EmptyState title="Nenhum artigo."/></TableCell></TableRow>:rows.map(a=><TableRow key={a.id}><TableCell><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>setSelected(ids=>ids.includes(a.id)?ids.filter(id=>id!==a.id):[...ids,a.id])}/></TableCell><TableCell><p className="font-medium">{a.title}</p><p className="text-xs text-slate-500">{a.category||"Sem categoria"}</p></TableCell><TableCell>{a.origin==="manual"?"Manual":"Importado"}</TableCell><TableCell>{a.editorial_status==="scheduled"?"Agendado":a.editorial_status==="draft"?"Rascunho":a.editorial_status==="published"?"Publicado":"Arquivado"}</TableCell><TableCell className="space-x-2 text-right"><Button size="icon" variant="ghost" title="Editar" className="rounded-full bg-amber-400 text-amber-950 hover:bg-amber-300" onClick={()=>openEditor(a)} disabled={a.origin!=="manual"}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" title="Duplicar" className="rounded-full bg-blue-600 text-white hover:bg-blue-700" onClick={()=>void duplicate(a)} disabled={a.origin!=="manual"}><Copy className="h-4 w-4"/></Button><Button size="sm" variant="outline" onClick={()=>void action(a,"published")}><Eye/>Publicar</Button><Button size="sm" variant="outline" onClick={()=>void action(a,"archived")}><Archive/>Arquivar</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>}
