# Generated by Django 5.2.10 on 2026-09-27 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('summary', models.CharField(blank=True, max_length=280)),
                ('body', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('info', 'Informativo'), ('maintenance', 'Manutenção'), ('news', 'Novidade'), ('urgent', 'Urgente'), ('required', 'Obrigatório')], default='info', max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendada'), ('published', 'Publicada'), ('closed', 'Encerrada'), ('archived', 'Arquivada')], db_index=True, default='draft', max_length=16)),
                ('scope', models.CharField(choices=[('all', 'Todos os usuários ativos'), ('selected_users', 'Usuários selecionados')], default='selected_users', max_length=20)),
                ('image_url', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('links', models.JSONField(blank=True, default=list)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('postpone_hours', models.PositiveSmallIntegerField(default=24)),
                ('max_postpones', models.PositiveSmallIntegerField(default=3)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_admin_notifications', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_admin_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='selected', max_length=20)),
                ('state', models.CharField(choices=[('pending', 'Pendente'), ('viewed', 'Visualizado'), ('postponed', 'Adiado'), ('dismissed', 'Dispensado')], db_index=True, default='pending', max_length=16)),
                ('first_shown_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('next_reminder_at', models.DateTimeField(blank=True, null=True)),
                ('postpone_count', models.PositiveSmallIntegerField(default=0)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.adminnotification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_notification_recipients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['notification', 'state'], name='notificatio_notific_d11533_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'user'), name='unique_admin_notification_recipient')],
            },
        ),
    ]
