# Generated by Django 5.2.10 on 2026-09-27 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_adminnotification_notificationrecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='closure_reason',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
