# Generated by Django 5.2.10 on 2026-09-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_adminnotification_closure_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnotification',
            name='segment_plan_slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name='adminnotification',
            name='segment_subscription_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='adminnotification',
            name='scope',
            field=models.CharField(choices=[('all', 'Todos os usuários ativos'), ('selected_users', 'Usuários selecionados'), ('segment', 'Segmento de assinatura')], default='selected_users', max_length=20),
        ),
    ]
