"use client";

import { useEffect, useState } from "react";
import { Bell, Plus, Send } from "lucide-react";
import { adminNotifications, AdminNotificationRow, backoffice, UserRow } from "@/lib/backoffice";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice } from "@/components/admin/Notice";

const empty = { title: "", summary: "", body: "", priority: "info", scope: "selected_users", segment_plan_slug: "", segment_subscription_status: "", starts_at: "", ends_at: "", selected_user_ids: [] as number[] };
const labels: Record<string, string> = { draft: "Rascunho", scheduled: "Agendado", published: "Publicado", closed: "Encerrado", archived: "Arquivado", info: "Informativo", maintenance: "Manutenção", news: "Novidade", urgent: "Urgente", required: "Obrigatório" };

export default function NotificationsPage() {
  const [userSearch, setUserSearch] = useState(""); const [items, setItems] = useState<AdminNotificationRow[]>([]); const [users, setUsers] = useState<UserRow[]>([]); const [plans, setPlans] = useState<{slug:string; name:string}[]>([]);
  const [form, setForm] = useState(empty); const [statusFilter, setStatusFilter] = useState(""); const [search, setSearch] = useState(""); const [editing, setEditing] = useState<AdminNotificationRow | null>(null); const [message, setMessage] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { const [notices, userList, planList] = await Promise.all([adminNotifications.list(), backoffice.listUsers(), backoffice.listPlans()]); setItems(notices.results); setUsers(userList.results); setPlans(planList.results); } catch { setMessage("Não foi possível carregar as notificações."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const visibleItems = items.filter(item => (!statusFilter || item.status === statusFilter) && (!search || item.title.toLowerCase().includes(search.toLowerCase())));
  const toggleVisible = () => setForm(current => { const ids = users.map(user => user.id); const allSelected = ids.every(id => current.selected_user_ids.includes(id)); return {...current, selected_user_ids: allSelected ? current.selected_user_ids.filter(id => !ids.includes(id)) : [...new Set([...current.selected_user_ids, ...ids])]}; });
  const searchUsers = async () => { const result = await backoffice.listUsers({search:userSearch, limit:50}); setUsers(result.results); };
  const toggleUser = (id:number) => setForm(current => ({ ...current, selected_user_ids: current.selected_user_ids.includes(id) ? current.selected_user_ids.filter(item => item !== id) : [...current.selected_user_ids, id] }));
  const save = async () => { try { if (editing) await adminNotifications.update(editing.id, {...form, starts_at: form.starts_at || null, ends_at: form.ends_at || null}); else await adminNotifications.create({...form, starts_at: form.starts_at || null, ends_at: form.ends_at || null}); setMessage("Rascunho salvo. Revise os destinatários antes de publicar."); setForm(empty); setEditing(null); await load(); } catch (error:any) { const data=error?.response?.data; setMessage(data?.title || data?.selected_user_ids || data?.detail || "Não foi possível salvar o aviso."); } };
  const edit = (item:AdminNotificationRow) => { setEditing(item); setForm({ title:item.title, summary:item.summary, body:item.body, priority:item.priority, scope:item.scope, segment_plan_slug:item.segment_plan_slug || "", segment_subscription_status:item.segment_subscription_status || "", starts_at:item.starts_at ? item.starts_at.slice(0, 16) : "", ends_at:item.ends_at ? item.ends_at.slice(0, 16) : "", selected_user_ids:item.selected_user_ids }); window.scrollTo({top:0, behavior:"smooth"}); };
  const publish = async (id:number) => { try { await adminNotifications.publish(id); setMessage("Aviso publicado para os destinatários selecionados."); await load(); } catch (error:any) { setMessage(error?.response?.data?.detail || "Não foi possível publicar o aviso."); } };
  const close = async (item:AdminNotificationRow) => { const reason = window.prompt(item.priority === "required" ? "Justificativa obrigatória para encerrar:" : "Motivo do encerramento (opcional):") || ""; try { await adminNotifications.close(item.id, reason); setMessage("Aviso encerrado."); await load(); } catch (error:any) { setMessage(error?.response?.data?.reason || error?.response?.data?.detail || "Não foi possível encerrar o aviso."); } };
  const archive = async (id:number) => { if (!window.confirm("Arquivar este aviso? O histórico será preservado.")) return; try { await adminNotifications.archive(id); setMessage("Aviso arquivado."); await load(); } catch { setMessage("Não foi possível arquivar o aviso."); } };
  return <div className="space-y-6"><PageHeader title="Notificações" description="Crie avisos in-app, escolha os usuários e acompanhe a confirmação." />
    {message && <Notice kind={message.includes("salvo") || message.includes("publicado") ? "success" : "error"}>{message}</Notice>}
    <section className="rounded-lg border p-5"><div className="mb-4 flex items-center justify-between"><h2 className="flex items-center gap-2 font-semibold"><Bell className="h-4 w-4" />{editing ? "Editar rascunho" : "Novo aviso"}</h2>{editing && <Button variant="outline" size="sm" onClick={() => {setEditing(null);setForm(empty)}}>Cancelar edição</Button>}</div>
      <div className="grid gap-3 md:grid-cols-2"><Input placeholder="Título obrigatório" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/><select className="rounded border px-3" value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}>{["info","maintenance","news","urgent","required"].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select><Input placeholder="Resumo opcional" value={form.summary} onChange={e=>setForm({...form,summary:e.target.value})}/><select className="rounded border px-3" value={form.scope} onChange={e=>setForm({...form,scope:e.target.value,selected_user_ids:e.target.value === "all" ? [] : form.selected_user_ids})}><option value="selected_users">Usuários selecionados</option><option value="all">Todos os usuários ativos</option><option value="segment">Segmento de assinatura</option></select><label className="text-sm">Início (opcional)<Input type="datetime-local" value={form.starts_at} onChange={e=>setForm({...form,starts_at:e.target.value})}/></label><label className="text-sm">Término (opcional)<Input type="datetime-local" value={form.ends_at} onChange={e=>setForm({...form,ends_at:e.target.value})}/></label><textarea className="min-h-24 rounded border p-3 md:col-span-2" placeholder="Texto do aviso (sem HTML nesta primeira versão)" value={form.body} onChange={e=>setForm({...form,body:e.target.value})}/></div>
      {form.scope === "segment" ? <div className="mt-4 grid gap-3 rounded border p-3 md:grid-cols-2"><label className="text-sm">Plano<select className="mt-1 h-9 w-full rounded border px-2" value={form.segment_plan_slug || ""} onChange={e=>setForm({...form,segment_plan_slug:e.target.value})}><option value="">Todos os planos</option>{plans.map(plan=><option key={plan.slug} value={plan.slug}>{plan.name}</option>)}</select></label><label className="text-sm">Status<select className="mt-1 h-9 w-full rounded border px-2" value={form.segment_subscription_status || ""} onChange={e=>setForm({...form,segment_subscription_status:e.target.value})}><option value="">Todos os status</option><option value="active">Ativa</option><option value="pending_payment">Pagamento pendente</option><option value="canceled">Cancelada</option></select></label><p className="text-xs text-slate-500 md:col-span-2">Informe ao menos um critério. Os destinatários serão definidos no momento da publicação.</p></div> : form.scope === "selected_users" ? <div className="mt-4 rounded border p-3"><p className="font-medium">Destinatários selecionados ({form.selected_user_ids.length})</p><div className="mb-2 flex gap-2"><Input className="h-8" placeholder="Buscar usuário" value={userSearch} onChange={e=>setUserSearch(e.target.value)} onKeyDown={e=>{if(e.key === "Enter") void searchUsers()}}/><Button size="sm" variant="outline" onClick={()=>void searchUsers()}>Buscar</Button><Button size="sm" variant="outline" onClick={toggleVisible}>Selecionar página</Button></div><p className="mb-2 text-sm text-slate-500">A lista é congelada ao publicar. O envio para todos os usuários será disponibilizado com o job assíncrono.</p><div className="max-h-44 space-y-1 overflow-y-auto">{users.map(user=><label key={user.id} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.selected_user_ids.includes(user.id)} onChange={()=>toggleUser(user.id)}/>{user.username} <span className="text-slate-500">{user.email}</span></label>)}</div></div> : <p className="mt-4 rounded border border-blue-200 bg-blue-50 p-3 text-sm text-blue-900">Ao publicar, os usuários ativos serão materializados em segundo plano. Este processamento não bloqueia o painel.</p>}
      <div className="mt-4 rounded border bg-slate-50 p-3 text-sm"><p className="font-medium">Prévia</p><p className="mt-1 text-base font-semibold">{form.title || "Título do aviso"}</p>{form.summary && <p className="text-slate-600">{form.summary}</p>}{form.body && <p className="mt-2 whitespace-pre-wrap">{form.body}</p>}<p className="mt-2 text-xs text-slate-500">Prioridade: {labels[form.priority]} · alcance: {form.scope === "all" ? "todos os usuários ativos" : `${form.selected_user_ids.length} usuário(s) selecionado(s)`}</p></div>
      <Button className="mt-4" onClick={()=>void save()} disabled={!form.title || (form.scope === "selected_users" && !form.selected_user_ids.length) || (form.scope === "segment" && !form.segment_plan_slug && !form.segment_subscription_status)}><Plus className="h-4 w-4" />Salvar rascunho</Button></section>
    <section><div className="mb-3 flex flex-wrap items-center justify-between gap-2"><h2 className="font-semibold">Avisos criados</h2><div className="flex gap-2"><Input className="h-9 w-48" placeholder="Buscar título" value={search} onChange={e=>setSearch(e.target.value)}/><select className="rounded border px-2 text-sm" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="">Todos os status</option>{["draft","scheduled","published","closed","archived"].map(value=><option key={value} value={value}>{labels[value]}</option>)}</select></div></div>{loading ? <p className="text-slate-500">Carregando…</p> : <div className="overflow-x-auto rounded border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Aviso</th><th>Status</th><th>Destinatários</th><th>Confirmações</th><th>Adiados</th><th className="p-3">Ações</th></tr></thead><tbody>{visibleItems.map(item=><tr key={item.id} className="border-b"><td className="p-3"><strong>{item.title}</strong><p className="text-slate-500">{labels[item.priority]}</p></td><td>{labels[item.status] || item.status}</td><td>{item.metrics.total}</td><td>{item.metrics.viewed}</td><td>{item.metrics.postponed}</td><td className="p-3 space-x-2">{["draft","scheduled"].includes(item.status) && <><button className="underline" onClick={()=>edit(item)}>Editar</button><button className="underline" onClick={()=>void publish(item.id)}><Send className="mr-1 inline h-3 w-3" />Publicar</button></>}{item.status === "published" && <button className="underline" onClick={()=>void close(item)}>Encerrar</button>}{["closed","draft","scheduled"].includes(item.status) && <button className="text-red-700 underline" onClick={()=>void archive(item.id)}>Arquivar</button>}</td></tr>)}{!visibleItems.length && <tr><td colSpan={6} className="p-5 text-slate-500">Nenhum aviso criado.</td></tr>}</tbody></table></div>}</section></div>;
}
