# Generated by Django 5.2.10 on 2026-09-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_profile_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_in_ranking',
            field=models.BooleanField(default=True),
        ),
    ]
