"use client";
import { FormEvent, useEffect, useState } from "react";
import { Eye, EyeOff, Pencil, Plus } from "lucide-react";
import { editorial, EditorialConcurso, EditorialExam } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice, LoadingState, EmptyState } from "@/components/admin/Notice";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default function ProvasPage() {
  const [rows, setRows] = useState<EditorialExam[]>([]); const [concursos, setConcursos] = useState<EditorialConcurso[]>([]); const [editing, setEditing] = useState<Partial<EditorialExam> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); try { const [provas, items] = await Promise.all([editorial.listExams(), editorial.listConcursos()]); setRows(provas.results); setConcursos(items.results); } catch { setError("Não foi possível carregar as provas."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const f = new FormData(event.currentTarget); const data = { title: String(f.get("title")), banca: String(f.get("banca")), year: Number(f.get("year")), institution: String(f.get("institution")), role: String(f.get("role")), level: String(f.get("level")), state: String(f.get("state")).toUpperCase(), concurso: f.get("concurso") ? Number(f.get("concurso")) : null, is_published: f.get("is_published") === "on" }; try { if (editing.id) await editorial.updateExam(editing.id, data); else await editorial.createExam(data); setEditing(null); setNotice("Prova salva."); void load(); } catch { setError("Revise título, banca, ano e vínculo antes de salvar."); } };
  const publish = async (row: EditorialExam) => { try { await editorial.updateExam(row.id, { is_published: !row.is_published }); void load(); } catch { setError("Não foi possível alterar a publicação."); } };
  return <div className="space-y-6"><PageHeader title="Provas" description="Organize metadados, vínculos com concursos e visibilidade das provas." actions={<Button onClick={() => setEditing({ title: "", banca: "", year: new Date().getFullYear(), institution: "", role: "", concurso: null, is_published: false })}><Plus /> Nova prova</Button>} />{error && <Notice kind="error">{error}</Notice>}{notice && <Notice kind="success">{notice}</Notice>}
    {editing && <Card><CardContent className="p-5"><form className="grid gap-3 sm:grid-cols-2" onSubmit={save}><Input name="title" required defaultValue={editing.title} placeholder="Título"/><Input name="banca" required defaultValue={editing.banca} placeholder="Banca"/><Input name="year" required type="number" min="1980" max="2100" defaultValue={editing.year} placeholder="Ano"/><Input name="institution" defaultValue={editing.institution} placeholder="Instituição"/><Input name="role" defaultValue={editing.role} placeholder="Cargo"/><Input name="level" placeholder="Nível"/><Input name="state" maxLength={2} placeholder="UF"/><select name="concurso" defaultValue={editing.concurso ?? ""} className="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Sem concurso vinculado</option>{concursos.map(c => <option value={c.id} key={c.id}>{c.title}</option>)}</select><label className="flex gap-2 text-sm sm:col-span-2"><input name="is_published" type="checkbox" defaultChecked={editing.is_published}/> Publicar esta prova para os alunos</label><div className="flex gap-2 sm:col-span-2"><Button type="submit">Salvar</Button><Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancelar</Button></div></form></CardContent></Card>}
    {loading ? <LoadingState /> : <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Prova</TableHead><TableHead>Concurso</TableHead><TableHead>Questões</TableHead><TableHead>Visibilidade</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={5}><EmptyState title="Nenhuma prova cadastrada." /></TableCell></TableRow> : rows.map(row => <TableRow key={row.id}><TableCell><p className="font-medium">{row.title}</p><p className="text-xs text-slate-500">{row.banca} · {row.year}</p></TableCell><TableCell>{concursos.find(c => c.id === row.concurso)?.title || "—"}</TableCell><TableCell>{row.questions_count}</TableCell><TableCell>{row.is_published ? "Publicada" : "Rascunho"}</TableCell><TableCell className="space-x-2 text-right"><Button size="sm" variant="outline" onClick={() => setEditing(row)}><Pencil /> Editar</Button><Button size="sm" variant="outline" onClick={() => void publish(row)}>{row.is_published ? <><EyeOff /> Ocultar</> : <><Eye /> Publicar</>}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>;
}
