# Generated by Django 5.2.10 on 2026-09-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('title', models.CharField(max_length=300)),
                ('organization', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField(blank=True)),
                ('headline', models.CharField(blank=True, max_length=160)),
                ('roles', models.JSONField(default=list)),
                ('levels', models.JSONField(default=list)),
                ('state', models.CharField(blank=True, db_index=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('open', 'Inscrições abertas'), ('expected', 'Autorizado / Previsto'), ('closed', 'Encerrado')], db_index=True, default='open', max_length=12)),
                ('deadline', models.DateField(blank=True, db_index=True, null=True)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('vacancies', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.IntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-fetched_at', '-id'],
                'indexes': [models.Index(fields=['state', 'status'], name='concursos_state_status_idx')],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_concurso_source')],
            },
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(db_index=True, max_length=32)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=260, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=64)),
                ('image_url', models.URLField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=600)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_at', '-fetched_at'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='unique_news_source')],
            },
        ),
    ]
