# Generated by Django 5.2.10 on 2026-09-27 20:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='concurso',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_concursos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='concurso',
            name='editorial_status',
            field=models.CharField(choices=[('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='concurso',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('imported', 'Importado')], db_index=True, default='imported', max_length=12),
        ),
        migrations.AddField(
            model_name='concurso',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_concursos', to=settings.AUTH_USER_MODEL),
        ),
    ]
