# Generated by Django 5.2.10 on 2026-09-27 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0002_editorial_concursos_provas'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_news', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='editorial_status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('scheduled', 'Agendado'), ('published', 'Publicado'), ('archived', 'Arquivado')], db_index=True, default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='origin',
            field=models.CharField(choices=[('manual', 'Manual'), ('imported', 'Importado')], db_index=True, default='imported', max_length=12),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
