# Generated by Django 5.2.10 on 2026-09-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concursos', '0003_editorial_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_pinned',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='seo_title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
