"use client";

import { useEffect, useMemo, useState } from "react";
import { auditAdmin, AuditEventRow } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export default function AuditPage() {
  const [rows, setRows] = useState<AuditEventRow[]>([]), [total, setTotal] = useState(0), [page, setPage] = useState(1), [action, setAction] = useState(""), [resource, setResource] = useState(""), [query, setQuery] = useState(""), [actor, setActor] = useState(""), [since, setSince] = useState(""), [until, setUntil] = useState(""), [selected, setSelected] = useState<AuditEventRow | null>(null), [error, setError] = useState("");
  const params = useMemo(() => ({ page, action, resource_type: resource, q: query, actor, since: since ? new Date(since).toISOString() : "", until: until ? new Date(until).toISOString() : "" }), [page, action, resource, query, actor, since, until]);
  const load = async (nextPage = page) => { try { setError(""); const response = await auditAdmin.list({ ...params, page: nextPage }); setRows(response.results); setTotal(response.total); setPage(nextPage); } catch { setError("Não foi possível consultar a auditoria."); } };
  useEffect(() => { void load(1); }, []);
  const exportQuery = new URLSearchParams(Object.entries({ ...params, page: "", export: "csv" }).filter(([, value]) => value)).toString();
  return <div className="space-y-6"><PageHeader title="Auditoria" description="Histórico imutável de ações administrativas. Dados sensíveis são redigidos." /><div className="grid gap-2 rounded-xl border p-4 md:grid-cols-3"><Input placeholder="Buscar ação, recurso ou motivo" value={query} onChange={(event) => setQuery(event.target.value)} /><Input placeholder="Ação exata" value={action} onChange={(event) => setAction(event.target.value)} /><Input placeholder="Tipo de recurso" value={resource} onChange={(event) => setResource(event.target.value)} /><Input placeholder="ID do ator" inputMode="numeric" value={actor} onChange={(event) => setActor(event.target.value)} /><Input type="datetime-local" aria-label="A partir de" value={since} onChange={(event) => setSince(event.target.value)} /><Input type="datetime-local" aria-label="Até" value={until} onChange={(event) => setUntil(event.target.value)} /><div className="flex gap-2 md:col-span-3"><Button onClick={() => void load(1)}>Aplicar filtros</Button><a className="rounded-md border px-3 py-2 text-sm font-medium" href={`/api/backoffice/audit/?${exportQuery}`}>Exportar CSV</a></div></div>{error && <p className="rounded-md bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<p className="text-sm text-slate-500">{total} evento(s) encontrado(s)</p><div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead><tr className="border-b text-left"><th className="p-3">Data</th><th>Ação</th><th>Recurso</th><th>Ator</th><th className="p-3">Detalhe</th></tr></thead><tbody>{rows.map((row) => <tr key={row.id} className="border-b"><td className="p-3 whitespace-nowrap">{new Date(row.created_at).toLocaleString("pt-BR")}</td><td>{row.action}</td><td>{row.resource_type} {row.resource_id && `#${row.resource_id}`}</td><td>{row.actor?.username || "Sistema"}</td><td className="p-3"><button className="underline" onClick={() => setSelected(row)}>Ver</button></td></tr>)}{!rows.length && <tr><td colSpan={5} className="p-5 text-slate-500">Nenhum evento encontrado.</td></tr>}</tbody></table></div><div className="flex gap-2"><Button variant="outline" disabled={page === 1} onClick={() => void load(page - 1)}>Anterior</Button><Button variant="outline" disabled={rows.length < 30} onClick={() => void load(page + 1)}>Próxima</Button></div>{selected && <section className="rounded-xl border p-4"><div className="flex justify-between gap-4"><h2 className="font-semibold">Evento #{selected.id}</h2><button className="underline" onClick={() => setSelected(null)}>Fechar</button></div>{selected.reason && <p className="mt-2"><strong>Motivo:</strong> {selected.reason}</p>}<div className="mt-3 grid gap-3 md:grid-cols-2"><pre className="overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">Antes{`\n${JSON.stringify(selected.before, null, 2)}`}</pre><pre className="overflow-auto rounded bg-slate-950 p-3 text-xs text-slate-100">Depois{`\n${JSON.stringify(selected.after, null, 2)}`}</pre></div></section>}</div>;
}
