# Generated by Django 5.2.10 on 2026-09-23 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_update_plan_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='checkout_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='subscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='gateway',
            field=models.CharField(choices=[('local', 'Local'), ('stripe', 'Stripe')], default='local', max_length=20),
        ),
        migrations.AddField(
            model_name='subscription',
            name='provider_subscription_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=128, unique=True)),
                ('type', models.CharField(choices=[('payment.succeeded', 'Pagamento confirmado'), ('payment.failed', 'Pagamento recusado'), ('subscription.canceled', 'Assinatura cancelada'), ('subscription.renewed', 'Subscricao renovada')], max_length=40)),
                ('payload', models.JSONField(default=dict)),
                ('processed', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='billing.subscription')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
