# Generated by Django 5.2.10 on 2026-09-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription_checkout_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='description',
            field=models.CharField(blank=True, default='', max_length=240),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('published', 'Publicado'), ('archived', 'Arquivado')], default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='plan',
            name='trial_days',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
