# Generated by Django 5.2.10 on 2026-09-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsubmission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='exam_submissions/'),
        ),
    ]
