# Generated by Django 5.2.10 on 2026-09-24 18:17

from django.db import migrations, models


def mark_legacy_as_finished(apps, schema_editor):
    SimulationRun = apps.get_model("workspace", "SimulationRun")
    SimulationRun.objects.exclude(status="finished").update(status="finished")


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_examsubmission_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationrun',
            name='banca',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='discipline',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='exam_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='question_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='question_ids',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='status',
            field=models.CharField(choices=[('in_progress', 'Em andamento'), ('finished', 'Concluído'), ('expired', 'Expirado')], default='in_progress', max_length=16),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='time_limit_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='simulationrun',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(mark_legacy_as_finished, migrations.RunPython.noop),
    ]
