# Generated by Django 5.2.10 on 2026-09-22 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=160)),
                ('exam_date', models.DateField(blank=True, null=True)),
                ('disciplines', models.JSONField(default=list)),
                ('weekdays', models.JSONField(default=list)),
                ('minutes_per_day', models.PositiveSmallIntegerField(default=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('discipline', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('theory', 'Teoria'), ('questions', 'Questões'), ('review', 'Revisão')], max_length=12)),
                ('planned_minutes', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluído'), ('skipped', 'Adiado')], default='pending', max_length=10)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='studies.studyplan')),
            ],
            options={
                'ordering': ['date', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.PositiveSmallIntegerField()),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='studies.studyblock')),
            ],
        ),
    ]
