# Generated by Django 5.2.10 on 2026-09-25 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studyplan',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='studyblock',
            name='cycle_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='cycle',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='kind',
            field=models.CharField(choices=[('trilha', 'Trilha semanal'), ('cronograma', 'Cronograma de estudos'), ('ciclo', 'Ciclo de estudos')], default='trilha', max_length=12),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='schedule',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='studyplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='StudyInterval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('minutes', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(choices=[('focus', 'Foco'), ('break', 'Descanso')], max_length=8)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='intervals', to='studies.studyplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_intervals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
