# Generated by Django 5.2.10 on 2026-09-22 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_exam_question_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='source_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
