# Generated by Django 5.2.10 on 2026-09-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_backfill_question_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnote',
            name='content',
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
