# Generated by Django 5.2.10 on 2026-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_alter_questionnote_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='errorreport',
            name='description',
            field=models.TextField(max_length=5000),
        ),
    ]
