# Generated by Django 5.2.10 on 2026-09-24 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0007_alter_comment_content_alter_errorreport_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('discipline', models.CharField(blank=True, default='', max_length=100)),
                ('exam_ids', models.JSONField(default=list)),
                ('banca', models.CharField(blank=True, default='', max_length=100)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('full_exam', models.BooleanField(default=False)),
                ('time_limit_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
