# Generated by Django 5.2.10 on 2026-09-26 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0012_normalize_question_bancas'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='review_note',
            field=models.TextField(blank=True),
        ),
    ]
