# Generated by Django 5.2.10 on 2026-09-27 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0018_official_exam_download'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialexamdownload',
            name='final_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
