# Generated by Django 5.2.10 on 2026-09-27 05:38

import apps.questions.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0019_official_exam_download_final_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialexamdownload',
            name='file',
            field=models.FileField(blank=True, storage=apps.questions.storages.PrivateOfficialExamStorage(), upload_to='official-exams/%Y/%m/'),
        ),
    ]
