# Generated by Django 5.2.10 on 2026-09-27 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0023_editorial_concursos_provas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[('draft', 'Rascunho'), ('pending', 'Na fila de aprovação'), ('approved', 'Aprovada'), ('rejected', 'Rejeitada')], db_index=True, default='pending', max_length=10),
        ),
    ]
