"use client";
import { FormEvent, useEffect, useState } from "react";
import { Pencil, Plus, Star } from "lucide-react";
import { bancasAdmin, BancaCatalogRow } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice, LoadingState, EmptyState } from "@/components/admin/Notice";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

type Editor = Partial<BancaCatalogRow> & { alias?: string };
export default function BancasPage() {
  const [rows, setRows] = useState<BancaCatalogRow[]>([]); const [editing, setEditing] = useState<Editor | null>(null); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(true);
  const load = async () => { setLoading(true); try { setRows((await bancasAdmin.list()).results); } catch { setError("Não foi possível carregar as bancas."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const form = new FormData(event.currentTarget); try { const data = { name: String(form.get("name")), slug: String(form.get("slug")), official_url: String(form.get("official_url")), description: String(form.get("description")), is_active: form.get("is_active") === "on", is_featured: form.get("is_featured") === "on" }; if (editing.id) { await bancasAdmin.update(editing.id, data); if (String(form.get("alias")).trim()) await bancasAdmin.addAlias(editing.id, String(form.get("alias"))); } else await bancasAdmin.create(data); setNotice("Banca salva com sucesso."); setEditing(null); void load(); } catch { setError("Não foi possível salvar. Verifique nome, slug, URL e aliases duplicados."); } };
  return <div className="space-y-6"><PageHeader title="Bancas" description="Gerencie nome canônico, aliases e disponibilidade sem alterar o histórico." actions={<Button onClick={() => setEditing({ name: "", slug: "", is_active: true })}><Plus /> Nova banca</Button>} />{error && <Notice kind="error">{error}</Notice>}{notice && <Notice kind="success">{notice}</Notice>}
    {editing && <Card><CardContent className="p-5"><form onSubmit={save} className="grid gap-3 sm:grid-cols-2"><Input name="name" required defaultValue={editing.name} placeholder="Nome canônico"/><Input name="slug" required defaultValue={editing.slug} placeholder="slug"/><Input name="official_url" type="url" defaultValue={editing.official_url} placeholder="Site oficial (opcional)"/><Input name="alias" placeholder="Novo alias (opcional)"/><Textarea name="description" defaultValue={editing.description} className="sm:col-span-2" placeholder="Descrição editorial"/><label className="flex gap-2 text-sm"><input name="is_active" type="checkbox" defaultChecked={editing.is_active}/> Ativa para novos cadastros</label><label className="flex gap-2 text-sm"><input name="is_featured" type="checkbox" defaultChecked={editing.is_featured}/> Destacar</label><div className="flex gap-2 sm:col-span-2"><Button type="submit">Salvar</Button><Button type="button" variant="outline" onClick={() => setEditing(null)}>Cancelar</Button></div></form></CardContent></Card>}
    {loading ? <LoadingState /> : <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Banca</TableHead><TableHead>Aliases</TableHead><TableHead>Uso</TableHead><TableHead>Status</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={5}><EmptyState title="Nenhuma banca catalogada." /></TableCell></TableRow> : rows.map(row => <TableRow key={row.id}><TableCell className="font-medium">{row.name}{row.is_featured && <Star className="ml-1 inline h-3 w-3 text-amber-500"/>}</TableCell><TableCell>{row.aliases.map(a => a.alias).join(", ") || "—"}</TableCell><TableCell>{row.questions_count} questões · {row.exams_count} provas</TableCell><TableCell>{row.is_active ? "Ativa" : "Inativa"}</TableCell><TableCell><Button size="sm" variant="outline" onClick={() => setEditing(row)}><Pencil /> Editar</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>;
}
