"use client";
import { FormEvent, useEffect, useState } from "react";
import { Archive, ArchiveRestore, Pencil, Plus } from "lucide-react";
import { editorial, EditorialConcurso } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice, LoadingState, EmptyState } from "@/components/admin/Notice";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent } from "@/components/ui/card";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default function ConcursosPage() {
  const [rows, setRows] = useState<EditorialConcurso[]>([]); const [editing, setEditing] = useState<Partial<EditorialConcurso> | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = async () => { setLoading(true); try { setRows((await editorial.listConcursos()).results); } catch { setError("Não foi possível carregar os concursos."); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  const save = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!editing) return; const f = new FormData(event.currentTarget); const data = { title: String(f.get("title")), organization: String(f.get("organization")), state: String(f.get("state")).toUpperCase(), status: String(f.get("status")), source_url: String(f.get("source_url")) }; try { if (editing.id) await editorial.updateConcurso(editing.id, data); else await editorial.createConcurso(data); setEditing(null); setNotice("Concurso salvo."); void load(); } catch { setError(editing.origin === "imported" ? "Concursos importados só permitem arquivamento editorial." : "Não foi possível salvar o concurso."); } };
  const archive = async (row: EditorialConcurso) => { try { await editorial.updateConcurso(row.id, { editorial_status: row.editorial_status === "archived" ? "published" : "archived" }); void load(); } catch { setError("Não foi possível atualizar o estado editorial."); } };
  const isImported = editing?.origin === "imported";
  return <div className="space-y-6"><PageHeader title="Concursos" description="Cadastre e mantenha concursos manuais; dados importados permanecem protegidos." actions={<Button onClick={() => setEditing({ title: "", organization: "", state: "", status: "expected", source_url: "", origin: "manual" })}><Plus /> Novo concurso</Button>} />{error && <Notice kind="error">{error}</Notice>}{notice && <Notice kind="success">{notice}</Notice>}
    {editing && <Card><CardContent className="p-5"><form className="grid gap-3 sm:grid-cols-2" onSubmit={save}><Input name="title" required defaultValue={editing.title} disabled={isImported} placeholder="Título"/><Input name="organization" defaultValue={editing.organization} disabled={isImported} placeholder="Órgão"/><Input name="state" maxLength={2} defaultValue={editing.state} disabled={isImported} placeholder="UF"/><select name="status" defaultValue={editing.status} disabled={isImported} className="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="expected">Previsto</option><option value="open">Inscrições abertas</option><option value="closed">Encerrado</option></select><Input name="source_url" type="url" defaultValue={editing.source_url} disabled={isImported} className="sm:col-span-2" placeholder="URL de referência"/><div className="flex gap-2 sm:col-span-2"><Button type="submit" disabled={isImported}>Salvar</Button><Button type="button" variant="outline" onClick={() => setEditing(null)}>Fechar</Button></div>{isImported && <p className="sm:col-span-2 text-xs text-slate-500">Este item é sincronizado. Seus campos de origem não podem ser editados aqui.</p>}</form></CardContent></Card>}
    {loading ? <LoadingState /> : <Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Concurso</TableHead><TableHead>Origem</TableHead><TableHead>Provas</TableHead><TableHead>Estado</TableHead><TableHead /></TableRow></TableHeader><TableBody>{rows.length === 0 ? <TableRow><TableCell colSpan={5}><EmptyState title="Nenhum concurso cadastrado." /></TableCell></TableRow> : rows.map(row => <TableRow key={row.id}><TableCell><p className="font-medium">{row.title}</p><p className="text-xs text-slate-500">{row.organization || "Órgão não informado"} {row.state && `· ${row.state}`}</p></TableCell><TableCell>{row.origin === "manual" ? "Manual" : "Importado"}</TableCell><TableCell>{row.exams_count}</TableCell><TableCell>{row.editorial_status === "archived" ? "Arquivado" : "Publicado"}</TableCell><TableCell className="space-x-2 text-right"><Button size="sm" variant="outline" onClick={() => setEditing(row)}><Pencil /> Detalhes</Button><Button size="sm" variant="outline" onClick={() => void archive(row)}>{row.editorial_status === "archived" ? <><ArchiveRestore /> Restaurar</> : <><Archive /> Arquivar</>}</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>;
}
