# Generated by Django 5.2.10 on 2026-09-28 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditevent',
            options={'ordering': ['-created_at', '-id'], 'permissions': [('view_financial_reports', 'Pode visualizar indicadores financeiros')]},
        ),
    ]
