"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { Pencil, Save, Send, ClipboardCheck } from "lucide-react";
import { bancasAdmin, editorial, manualQuestions, ManualQuestion } from "@/lib/backoffice";
import { PageHeader } from "@/components/admin/PageHeader";
import { Notice, LoadingState, EmptyState } from "@/components/admin/Notice";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

export default function ManualQuestionsPage() {
 const [items,setItems]=useState<ManualQuestion[]>([]),[editing,setEditing]=useState<Partial<ManualQuestion> | null>({status:"draft",statement:"",banca:"",discipline:"",year:new Date().getFullYear(),options:[],correct_answer:0,source_url:""}),[bancas,setBancas]=useState<string[]>([]),[exams,setExams]=useState<Awaited<ReturnType<typeof editorial.listExams>>["results"]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[notice,setNotice]=useState("");
 const load=async()=>{setLoading(true);try{const [questions,catalog,proofs]=await Promise.all([manualQuestions.list(),bancasAdmin.list(),editorial.listExams()]);setItems(questions.results);setBancas(catalog.results.filter(b=>b.is_active).map(b=>b.name));setExams(proofs.results)}catch{setError("Não foi possível carregar os dados do cadastro.")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);
 const save=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editing)return;const f=new FormData(e.currentTarget);const data={statement:String(f.get("statement")),banca:String(f.get("banca")),discipline:String(f.get("discipline")),year:Number(f.get("year")),options:String(f.get("options")).split("\n").map(x=>x.trim()).filter(Boolean),correct_answer:Number(f.get("correct_answer"))-1,source_url:String(f.get("source_url")),explanation:String(f.get("explanation")),number:f.get("number")?Number(f.get("number")):null,exam:f.get("exam")?Number(f.get("exam")):null};try{if(editing.id)await manualQuestions.update(editing.id,data);else await manualQuestions.create(data);setEditing(null);setNotice("Rascunho salvo. Envie-o para a fila quando estiver revisado.");void load()}catch{setError("Revise enunciado, alternativas, gabarito, referência e duplicidade antes de salvar.")}};
 const submit=async(item:ManualQuestion)=>{try{await manualQuestions.submit(item.id);setNotice("Questão enviada à fila de revisão.");void load()}catch{setError("Não foi possível enviar a questão.")}};
 return <div className="space-y-6"><PageHeader title="Questões manuais" description="Rascunhos podem ser alterados; aprovação continua exclusiva da fila." actions={<Button asChild variant="outline"><Link href="/admin/fila-questoes?fonte=manual"><ClipboardCheck/>Abrir fila</Link></Button>}/>{error&&<Notice kind="error">{error}</Notice>}{notice&&<Notice kind="success">{notice}</Notice>}
 {editing&&<Card><CardContent className="p-5"><form onSubmit={save} className="space-y-3"><Textarea name="statement" required defaultValue={editing.statement} className="min-h-28" placeholder="Enunciado"/><div className="grid gap-3 sm:grid-cols-3"><Input name="banca" list="bancas" required defaultValue={editing.banca} placeholder="Banca"/><datalist id="bancas">{bancas.map(b=><option key={b} value={b}/>)}</datalist><Input name="discipline" required defaultValue={editing.discipline} placeholder="Disciplina"/><Input name="year" type="number" required defaultValue={editing.year}/></div><Textarea name="options" required defaultValue={editing.options?.join("\n")} placeholder="Alternativas, uma por linha"/><div className="grid gap-3 sm:grid-cols-2"><Input name="correct_answer" type="number" min="1" required defaultValue={(editing.correct_answer??0)+1} placeholder="Alternativa correta"/><Input name="source_url" type="url" required defaultValue={editing.source_url} placeholder="URL de referência"/><Input name="number" type="number" defaultValue={editing.number??""} placeholder="Número na prova"/><select name="exam" defaultValue={editing.exam_id??""} className="h-9 rounded-md border bg-transparent px-3 text-sm"><option value="">Sem prova vinculada</option>{exams.map(p=><option key={p.id} value={p.id}>{p.title} · {p.banca} ({p.year})</option>)}</select></div><Textarea name="explanation" defaultValue={editing.explanation} placeholder="Explicação para revisão"/><div className="flex gap-2"><Button type="submit"><Save/>Salvar rascunho</Button><Button type="button" variant="outline" onClick={()=>setEditing(null)}>Cancelar</Button></div></form></CardContent></Card>}
 {loading?<LoadingState/>:<Card><CardContent className="p-0"><Table><TableHeader><TableRow><TableHead>Questão</TableHead><TableHead>Contexto</TableHead><TableHead>Status</TableHead><TableHead/></TableRow></TableHeader><TableBody>{items.length===0?<TableRow><TableCell colSpan={4}><EmptyState title="Nenhum rascunho manual."/></TableCell></TableRow>:items.map(item=><TableRow key={item.id}><TableCell className="max-w-md truncate">{item.statement}</TableCell><TableCell>{item.banca} · {item.year}<p className="text-xs text-slate-500">{item.discipline}</p></TableCell><TableCell>{item.status==="draft"?"Rascunho":item.status==="pending"?"Na fila":item.status}</TableCell><TableCell className="space-x-2 text-right">{(item.status==="draft"||item.status==="rejected")&&<><Button size="sm" variant="outline" onClick={()=>setEditing(item)}><Pencil/>Editar</Button><Button size="sm" onClick={()=>void submit(item)}><Send/>Enviar</Button></>}</TableCell></TableRow>)}</TableBody></Table></CardContent></Card>}</div>;
}
