"use client";

import { Check, Plus, Search, X } from "lucide-react";

type Props = { label: string; value: string; search: string; options: string[]; placeholder: string; onSearchChange: (value: string) => void; onValueChange: (value: string) => void };
export function SearchableSingleSelect({ label, value, search, options, placeholder, onSearchChange, onValueChange }: Props) {
  const normalized = search.trim().toLocaleLowerCase("pt-BR");
  const matches = options.filter((item) => !normalized || item.toLocaleLowerCase("pt-BR").includes(normalized)).slice(0, 12);
  const exact = options.some((item) => item.toLocaleLowerCase("pt-BR") === normalized);
  const choose = (item: string) => { onValueChange(item); onSearchChange(""); };
  return <div><label className="mb-2 block text-sm font-semibold">{label}</label><div className="rounded-xl border border-slate-200 bg-white p-3 shadow-sm dark:border-slate-700 dark:bg-slate-900">{value && <div className="mb-3 flex"><span className="inline-flex items-center gap-1 rounded-lg bg-blue-100 py-1 pl-2 pr-1 text-sm font-semibold text-blue-800 dark:bg-blue-950/70 dark:text-blue-200">{value}<button type="button" onClick={() => onValueChange("")} className="rounded-md p-0.5 hover:bg-blue-200 focus:outline-none focus:ring-2 focus:ring-blue-500 dark:hover:bg-blue-900" aria-label={`Remover ${value}`}><X size={14} /></button></span></div>}<div className="relative"><Search size={17} aria-hidden="true" className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" /><input value={search} onChange={(event) => onSearchChange(event.target.value)} className="h-10 w-full rounded-lg border border-slate-300 bg-transparent pl-10 pr-3 text-sm outline-none focus:border-blue-500 focus:ring-2 focus:ring-blue-100 dark:border-slate-700 dark:focus:ring-blue-950" placeholder={placeholder} autoComplete="off" /></div>{search.trim() && <div className="mt-2 max-h-44 overflow-y-auto rounded-lg border border-slate-200 p-1 dark:border-slate-700">{matches.map((item) => <button key={item} type="button" onClick={() => choose(item)} className="flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm hover:bg-blue-50 focus:bg-blue-50 focus:outline-none dark:hover:bg-slate-800 dark:focus:bg-slate-800"><span>{item}</span>{item === value ? <Check size={16} className="text-emerald-600" /> : <Plus size={16} className="text-blue-600" />}</button>)}{!exact && <button type="button" onClick={() => choose(search.trim())} className="flex w-full items-center gap-2 rounded-md px-3 py-2 text-left text-sm font-medium text-blue-700 hover:bg-blue-50 dark:text-blue-300 dark:hover:bg-slate-800"><Plus size={16} />Usar “{search.trim()}”</button>}{matches.length === 0 && exact && <p className="px-3 py-2 text-sm text-slate-500">Nenhuma opção encontrada.</p>}</div>} {!search.trim() && <p className="mt-2 text-xs text-slate-500">Pesquise pelo nome e selecione uma opção.</p>}</div></div>;
}
